### PR TITLE
Update GalSimWCS wrapper to handle new DESMaps class

### PR DESCRIPTION
**Pull request by rmjarvis**
@rgruendl wants to use Piff with the new DESMaps class for the DES Y6 solution.  However, Piff depends on the GalSimWCS class to read in the PixelMapCollection, which only works with the normal one, not the new DESMaps class.

I think this PR fixes this.  I added some unit tests, but the real test of the new functionality here is in the examples directory, rather than tests.  We should really have small versions of the new files that can comfortably live in the test directory of the repo to validate the functionality.

For now, my only real test is running `galsim wrong_wcs.yaml` in the `examples` directory.  This is a GalSim config file that uses Y6 DES Pixmappy for the real wcs, but writes out a wrong wcs into the FITS header.  It's not really very interesting.  It's a massively reduced version of something I wrote a while back, which lives in the galsim_extra repo.  I cut out most of the the complicated bits, so I could just test the Pixmappy wcs type.  I think it's all working properly.

For Robert, if you want to try using this with Piff on Y6A1, the bits you need in the piff config file are:
```
modules:
    - pixmappy

input:
    # All the normal stuff here.

    wcs:
        type: Pixmappy
        dir: /Path/To/Y6A1_ASTROMETRY
        file_name: y6a1.guts.astro
        exposure_file: y6a1.exposureinfo.fits
        affine_file: y6a1.affine.fits
        resids_file: y6a1.astroresids.fits
        exp: 12345   # Set this appropriately for each file
        ccdnum: 1    # Set this appropriately for each file
```
Then you'd probably want to set `exp` and `ccdnum` from the command line:
```
piffify piff.yaml input.wcs.exp=exp input.wcs.ccdnum=ccdnum
```
Using some bash scripting to figure out the right values for these each time.

### CODE REVIEW

**Comment by esheldon** [comment]
Actually that works for `None` also, so you can reduce it to

`if np.ndim(c) == 0`

**Comment by esheldon** [comment]
Can we merge this and make a tag for DESDM to use?

**Comment by gbernstein** [comment]
Thanks for the nag, I've been procrastinating this.  I'll get on it today.  If you want to do this soon (like today or tomorrow), we can just do the merge since we already know the code works, and I'll review the code and make any necessary changes on the master branch after merge.

**Comment by esheldon** [comment]
I'm not sure DESDM can work from branches, they might need tags.  I'll ask

**Comment by gbernstein** [comment]
Question for @rmjarvis @esheldon : I would like to change the interface for `GalSimWCS`.  Right now it has an argument `exposure_file` which triggers 2 possible behaviors:
* if `exposure_file=None`, then it assumes that the input `file_name` is a regular map collection.  This is the default.
* if not, it assumes that it will be reading the building the maps from the Y6A1 astrometry release tables that I made, and that `file_name` is part of the input needed to use the `DESMaps` class.

The problem is that I would like there to be a simple default whereby the Y6A1 files are used and the user does not need to know the magic filenames that are part of that release - they'll be taken from some defaults built into the release.  So I'd like to change the constructor for this class to have the following arguments instead:
`def __init__(self, useDES=False, file_name=None, guts_file=None, resids_file=None, \`
`                        affine_file=None, exposure_file=None, ...)`

If you supply only `file_name` then the behavior is as before: this file is read for pixel maps without using the Y6A1 table.    But if you call with `useDES=True` it will use the `DESMaps` class and will use the default names for any of the guts/resids/affine/exposure files that you did not specify explicitly.  This would require adding `useDES=True` to the calls in codes that are currently using the Y6A1 astrometry release.  Is that OK?  Or would it be better to set the default as `useDES=True` so that Y6A1 is used?

**Comment by rmjarvis** [comment]
I think all pixmappy stuff (so far) is DES, so `useDES` is a bit ambiguous.  Maybe `useDESY6` would be clearer?  
And I would probably suggest having the default be False to force the user to specify at least something.  I.e. `pixmappy.GalSimWCS()` should probably be an error.  The user should specify something to indicate which file(s) they want.

**Comment by gbernstein** [comment]
Another question for @rmjarvis :  the `origin` member of `GalSimWCS` is never used in the coordinate transformations, it just seems to be a value that is kept track of.  Is that the desired behavior?

**Comment by rmjarvis** [comment]
> the origin member of GalSimWCS is never used in the coordinate transformations

Good catch.  I think that's probably an oversight on my part.  Let me look into it.

**Comment by gbernstein** [comment]
I just pushed a large set of revisions to github, so you can make changes on that.
Could you also check whether the changes I made to galsim_config.py make sense?

On Jan 17, 2020, at 11:10 PM, Mike Jarvis <notifications@github.com<mailto:notifications@github.com>> wrote:


the origin member of GalSimWCS is never used in the coordinate transformations

Good catch. I think that's probably an oversight on my part. Let me look into it.

**Review by gbernstein — APPROVED** [review]
All changes look good.  The only outstanding issue is whether `GalSimWCS` needs to use its origin member during transformations.

**Comment by gbernstein** [comment]
All of the galsim_update changes have now been merged into master and tagged as the v1.0.0 release.


On Jan 15, 2020, at 11:20 AM, Erin Sheldon <notifications@github.com<mailto:notifications@github.com>> wrote:


Can we merge this and make a tag for DESDM to use?

**Pull request merged**
